workflows:
  ios-workflow:
    name: Build iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios
    artifacts:
      - build/ios/ipa/*.ipa
    signing:
      ios:
        distribution_certificate:
          base64: $CM_CERTIFICATE_BASE64
          certificate_password: $CERT_PASSWORD
        provisioning_profile:
          base64: $CM_PROFILE_BASE64
        apple_signing: true
